---
abstract: Perl interface to CMIS-compliant document management systems
author:
  - 'Michael Daum <daum@michaeldaumconsulting.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Class: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Cmis
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
